input :
  - "input/containers"
  - "input/slot_profiles"
  - "input/train"
  - "input/test"
output : 
  - "output/sol"
  - "output/scores"
model :
  time_overstow_factor : 100000
  weight_overstow_factor : 70
  type_overstow_factor : 50
  mark_overstow_factor : 30
  empty_row_factor : 10000000000
